name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda
        run: |
          mkdir -p build
          cd lambdas/analyze
          zip -r ../../build/analyze.zip .

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name analyze \
            --zip-file fileb://build/analyze.zip

      - name: Update Lambda Handler
        run: |
          aws lambda update-function-configuration \
            --function-name analyze \
            --handler handler.lambda_handler
